org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.showThreadName=false

org.slf4j.simpleLogger.log.org.example.fiveletters.solving.beginningsearch.service.LetterFrequencyUniqueBeginningProducer=info
org.slf4j.simpleLogger.log.org.example.fiveletters.solving.beginningsearch.service.BruteForceUniqueBeginningProducer=info
org.slf4j.simpleLogger.log.org.example.fiveletters.solving.engine.service.ActionFilteringService=info
org.slf4j.simpleLogger.log.org.example.fiveletters.solving.research.service.StatsCalculator=debug
